Repository Shabbir136/Unknown, pull requests merged in 2020-10, with the labels that each got.

#3 Update Code.html
  Code.html
Labels: Hactoberfest-accepted

#4 Update Code.html
  Code.html
Labels: Hactoberfest-accepted

#5 Update Code.html
  Code.html
Labels: Hactoberfest-accepted

#6 Update Code.html
  Code.html
Labels: Hactoberfest-accepted

#7 Update code.html
  Code.html
Labels: hactoberfest-accepted

#8 Updated main.html
  Code.html
Labels: hacktoberfest-accepted

#9 Update Code.html
  Code.html
Labels: hacktoberfest-accepted
